apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-app-demo
  namespace: staging-demo
  labels:
    app: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: app-demo
          image: runechang/spinnaker-app-demo:staging
          resources:
            requests:
              memory: "512Mi"
              cpu: 0.1
            limits:
              memory: "512Mi"
              cpu: 0.1